### ISSUE TITLE
Add configuration to mark all local addresses as safe

### ISSUE THREAD

**Issue by mikecmpbll** [sdsdkkk/safe_redirect#6]
Probably use regexp here https://github.com/rack/rack/blob/ea9e7a570b7ffd8ac6845a9ebecdd7de0af6b0ca/lib/rack/request.rb#L420

**Comment by sdsdkkk** [comment]
Hi @mikecmpbll, sorry for the late response. Would you mind to review PR #7?

**Comment by mikecmpbll** [comment]
@sdsdkkk not at all! looks great to me 😍

**Comment by sdsdkkk** [comment]
Merged and published as v0.2.5. Thanks for the idea!
